---
title: "ebird"
author: "LH"
date: "2023-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r}
#install.packages("auk")
library(auk)
library(here)
```

Alabama test
```{r}
# locate data files
f_in <- system.file(here("data", 
                         "input", 
                         "ebd-datafile-SAMPLE", 
                         "ebd_US-AL-101_202204_202204_relApr-2022_SAMPLE", 
                         "ebd_US-AL-101_202204_202204_relApr-2022.txt"), 
                    package = "auk")

f_in <- system.file("data/input/ebd-datafile-SAMPLE/ebd_US-AL-101_202204_202204_relApr-2022_SAMPLE/ebd_US-AL-101_202204_202204_relApr-2022.txt", package = "auk")

test_txt <- read.table("data", "input", "ebd-datafile-SAMPLE", "ebd_US-AL-101_202204_202204_relApr-2022_SAMPLE", "ebd_US-AL-101_202204_202204_relApr-2022.txt", fill = TRUE)

f_in <- system.file(test_txt)

# output
f_out <- "ebd_filtered_AL.txt"


ebd <- auk_ebd(f_in) %>% 

auk_ebd() %>% # 1. reference file
  
# 2. define filters
auk_bbox(bbox = c(-86.212723, 34.563571, 86.242991, 34.581372)) %>% # bounding box for Alabama

  
# 3. run filtering
auk_filter(file = f_out) %>% 
  
# 4. read text file into r data frame
read_ebd()
```

SMF bbox:

top left:
 lat: 34.465504°
 long: -119.771787°
 
bottom right: 
  lat:  34.454424°
  long: -119.750857°
  
c(lng_min, lat_min, lng_max, lat_max)
c(-119.750857, 34.454424, 119.771787, 4.465504)
  
------------------------------

Alabama test bbox (Cathedral Caverns State Park):

top left:
  lat:  34.581372°
  long: -86.242991°
  
bottom right:
  lat:  34.563571°
  long: -86.212723°
  
c(-86.212723, 34.563571, 86.242991, 34.581372)
  
  
  